In [1]:
# Folium 라이브러리 탑재
import folium

# 기본 서울 지도 그래프 표기
seoul = folium.Map(location=[37.55, 126.98], zoom_start = 12)
seoul

In [145]:
# 판다스 라이브러리 탑재
import pandas as pd

# 승하차 인원 CSV 파일 읽어오기
data = pd.read_csv("C:\data\seoul-metro-2021.logs.csv")

# 데이터 확인하기
data

                             timestamp  station_code  people_in  people_out
0        2021-01-01T05:00:00.000+09:00           150         86          85
1        2021-01-01T06:00:00.000+09:00           150        111         355
2        2021-01-01T07:00:00.000+09:00           150        157         438
3        2021-01-01T08:00:00.000+09:00           150        306         592
4        2021-01-01T09:00:00.000+09:00           150        333         841
...                                ...           ...        ...         ...
1941548  2021-12-31T19:00:00.000+09:00          2828         74         263
1941549  2021-12-31T20:00:00.000+09:00          2828         73         145
1941550  2021-12-31T21:00:00.000+09:00          2828         95         209
1941551  2021-12-31T22:00:00.000+09:00          2828         54         138
1941552  2021-12-31T23:00:00.000+09:00          2828         18          34

[1941553 rows x 4 columns]

In [146]:
# 지하철역 정보 CSV 파일 읽어오기
station_info = pd.read_csv("C:\data\seoul-metro-station-info.csv")

# 데이터 확인하기
station_info

,station.code,station.fr_code,line.num,line.name,line.name_sub,line.station_seq,station.name_full,station.name,station.name_chc,station.name_chn,station.name_en,station.name_jp,geo.latitude,geo.longitude,geo.sigungu_code,geo.sigungu_name,geo.addres_road,geo.address_land,geo.phone
0,158,124,1,1호선,지하철1호선,1,청량리(서울시립대입구),청량리|서울시립대입구,祭基洞,祭基洞,Jegidong,チェギドン,37.580178,127.046835,11060,동대문구,서울특별시 동대문구 왕산로 지하205(전농동),서울특별시 동대문구 전농동 620-69 청량리역(1호선),02-6110-1241
1,157,125,1,1호선,지하철1호선,2,제기동,제기동,新設洞,新设洞,Sinseoldong,シンソルトン,37.578103,127.034893,11060,동대문구,서울특별시 동대문구 왕산로 지하93(제기동),서울특별시 동대문구 제기동 65 제기동역(1호선),02-6110-1251
2,156,126,1,1호선,지하철1호선,3,신설동,신설동,東廟앞,东庙,Dongmyo,トンミョアプ,37.575297,127.025087,11060,동대문구,서울특별시 동대문구 왕산로 지하1(신설동),서울특별시 동대문구 신설동 76-5 신설동역(1호선),02-6110-1261
3,159,127,1,1호선,지하철1호선,4,동묘앞,동묘앞,淸凉里(서울市立大入口),清凉里(首尔市立大学),Cheongnyangni(University of Seoul),チョンニャンニ,37.572627,127.016429,11010,종로구,서울특별시 종로구 종로 359(숭인동),서울특별시 종로구 숭인동 117 동묘앞역(1호선),02-6110-1271
4,155,128,1,1호선,지하철1호선,5,동대문,동대문,東大門,东大门,Dongdaemun,トンデムン,37.571420,127.009745,11010,종로구,서울특별시 종로구 종로 지하302(창신동),서울특별시 종로구 창신동 492-1 동대문역(1호선),02-6110-1281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,2823,823,8,8호선,지하철8호선,14,남한산성입구(성남법원.검찰청),남한산성입구|성남법원|검찰청,南漢山城入口(城南法院檢察廳),南汉山城(城南法院·检察厅),Namhansanseong(Seongnam Court & Prosecutors' O...,ナムハンサンソンイック,37.451535,127.159816,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하445(단대동),경기도 성남시 수정구 단대동 96 남한산성입구역(8호선),02-6311-8231
281,2824,824,8,8호선,지하철8호선,15,단대오거리,단대오거리,丹垈오거리,丹垈五岔路口,Dandaeogeori,タンデオゴリ,37.445210,127.156866,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하365(신흥동),경기도 성남시 수정구 신흥동 2467 단대오거리역(8호선),02-6311-8241
282,2825,825,8,8호선,지하철8호선,16,신흥,신흥,新興,新兴,Sinheung,シンフン,37.440918,127.147564,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하280(신흥동),경기도 성남시 수정구 신흥동 2467 신흥역(8호선),02-6311-8251
283,2826,826,8,8호선,지하철8호선,17,수진,수진,壽進,寿进,Sujin,スジン,37.437428,127.140722,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하200(수진동),경기도 성남시 수정구 수진동 2205-1 수진역(8호선),02-6311-8261
284,2827,827,8,8호선,지하철8호선,18,모란,모란,牡丹,牡丹,Moran,モラン,37.432130,127.129087,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하100(수진동),경기도 성남시 수정구 수진동 4518 모란역(8호선),02-6311-8271

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1941553 entries, 0 to 1941552
Data columns (total 4 columns):
 #   Column        Dtype
---  ------        -----
 0   timestamp     object
 1   station_code  int64
 2   people_in     int64
 3   people_out    int64
dtypes: int64(3), object(1)
memory usage: 59.3+ MB

In [5]:
# 승하차 인원 그룹화하여 더하기
station_sum = data.groupby("station_code").sum()

# 데이터 확인하기
station_sum

,timestamp,people_in,people_out
station_code,,,
150,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,12697273,12109991
151,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,5997344,6030491
152,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,9638952,9284693
153,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,7704599,7090896
154,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,6651283,6609055
...,...,...,...
2824,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,3206211,3097722
2825,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,1395919,1495603
2826,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,1614590,1475010
2827,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,1444073,1147602
2828,2021-12-14T05:00:00.000+09:002021-12-14T06:00:...,41623,46621

In [7]:
# 지하철역 정보 확인하기
station_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   station.code       285 non-null    int64
 1   station.fr_code    285 non-null    object
 2   line.num           285 non-null    int64
 3   line.name          285 non-null    object
 4   line.name_sub      285 non-null    object
 5   line.station_seq   285 non-null    int64
 6   station.name_full  285 non-null    object
 7   station.name       285 non-null    object
 8   station.name_chc   285 non-null    object
 9   station.name_chn   285 non-null    object
 10  station.name_en    285 non-null    object
 11  station.name_jp    285 non-null    object
 12  geo.latitude       285 non-null    float64
 13  geo.longitude      285 non-null    float64
 14  geo.sigungu_code   285 non-null    int64
 15  geo.sigungu_name   285 non-null    object
 16  geo.addres_road    285 non-null    object
 17  geo.address_land   285 non-null    object
 18  geo.phone          285 non-null    object
dtypes: float64(2), int64(4), object(13)
memory usage: 42.4+ KB

In [11]:
# 필요한 행만 추리기
station_info = station_info[['station.code','geo.latitude','geo.longitude']]

# 데이터 확인하기
station_info

     station.code  geo.latitude  geo.longitude
0             158     37.580178     127.046835
1             157     37.578103     127.034893
2             156     37.575297     127.025087
3             159     37.572627     127.016429
4             155     37.571420     127.009745
..            ...           ...            ...
280          2823     37.451535     127.159816
281          2824     37.445210     127.156866
282          2825     37.440918     127.147564
283          2826     37.437428     127.140722
284          2827     37.432130     127.129087

[285 rows x 3 columns]

In [12]:
# 색인 변경하기
station_info = station_info.set_index('station.code')

# 데이터 확인하기
station_info

              geo.latitude  geo.longitude
station.code
158              37.580178     127.046835
157              37.578103     127.034893
156              37.575297     127.025087
159              37.572627     127.016429
155              37.571420     127.009745
...                    ...            ...
2823             37.451535     127.159816
2824             37.445210     127.156866
2825             37.440918     127.147564
2826             37.437428     127.140722
2827             37.432130     127.129087

[285 rows x 2 columns]

In [14]:
# 데이터 셋 합치기
joined_data = station_sum.join(station_info)

# 데이터 확인하기
joined_data

,timestamp,people_in,people_out,geo.latitude,geo.longitude
station_code,,,,,
150,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,12697273,12109991,37.554648,126.972559
151,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,5997344,6030491,37.564718,126.977108
152,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,9638952,9284693,37.570161,126.982923
153,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,7704599,7090896,37.571607,126.991806
154,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,6651283,6609055,37.570926,127.001849
...,...,...,...,...,...
2824,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,3206211,3097722,37.445210,127.156866
2825,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,1395919,1495603,37.440918,127.147564
2826,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,1614590,1475010,37.437428,127.140722
2827,2021-01-01T05:00:00.000+09:002021-01-01T06:00:...,1444073,1147602,37.432130,127.129087
2828,2021-12-14T05:00:00.000+09:002021-12-14T06:00:...,41623,46621,37.463170,127.139526

In [15]:
# 승차용 서울 지도 만들기
seoul_in = folium.Map(location=[37.55, 126.98], zoom_start = 12)

# 지도 확인하기
seoul_in

In [16]:
# 히트맵 플러그인 모듈 탑재
from folium.plugins import HeatMap

# 히트맵 플러그인 지도에 추가하기
HeatMap(data = joined_data[['geo.latitude', 'geo.longitude', 'people_in']]).add_to(seoul_in)

# 지도 확인하기
seoul_in

In [20]:
# 하차용 지도 생성
seoul_out = folium.Map(location=[37.55, 126.98], zoom_start = 12)

# 히트맵 지도에 추가하기
HeatMap(data = joined_data[['geo.latitude', 'geo.longitude', 'people_out']]).add_to(seoul_out)

# 지도 확인하기
seoul_out

In [21]:
# 데이터 상세 정보 확인하기
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1941553 entries, 0 to 1941552
Data columns (total 4 columns):
 #   Column        Dtype
---  ------        -----
 0   timestamp     object
 1   station_code  int64
 2   people_in     int64
 3   people_out    int64
dtypes: int64(3), object(1)
memory usage: 59.3+ MB

In [22]:
# 출근용 데이터 추출
morning_data = data[pd.to_datetime(data.timestamp).dt.hour < 9]
morning_data

                             timestamp  station_code  people_in  people_out
0        2021-01-01T05:00:00.000+09:00           150         86          85
1        2021-01-01T06:00:00.000+09:00           150        111         355
2        2021-01-01T07:00:00.000+09:00           150        157         438
3        2021-01-01T08:00:00.000+09:00           150        306         592
19       2021-01-01T05:00:00.000+09:00           151         43          40
...                                ...           ...        ...         ...
1941518  2021-12-31T08:00:00.000+09:00          2827        391         311
1941534  2021-12-31T05:00:00.000+09:00          2828         20          10
1941535  2021-12-31T06:00:00.000+09:00          2828         83          41
1941536  2021-12-31T07:00:00.000+09:00          2828        279         119
1941537  2021-12-31T08:00:00.000+09:00          2828        347         375

[408748 rows x 4 columns]

In [23]:
# 퇴근용 데이터 추출
evening_data = data[pd.to_datetime(data.timestamp).dt.hour < 17]
evening_data

                             timestamp  station_code  people_in  people_out
0        2021-01-01T05:00:00.000+09:00           150         86          85
1        2021-01-01T06:00:00.000+09:00           150        111         355
2        2021-01-01T07:00:00.000+09:00           150        157         438
3        2021-01-01T08:00:00.000+09:00           150        306         592
4        2021-01-01T09:00:00.000+09:00           150        333         841
...                                ...           ...        ...         ...
1941541  2021-12-31T12:00:00.000+09:00          2828        192         124
1941542  2021-12-31T13:00:00.000+09:00          2828        189         159
1941543  2021-12-31T14:00:00.000+09:00          2828        198         228
1941544  2021-12-31T15:00:00.000+09:00          2828        227         213
1941545  2021-12-31T16:00:00.000+09:00          2828        218         341

[1226244 rows x 4 columns]

In [41]:
# 역 기준으로 그룹화하여 데이터 더하기 
morning_station_sum = morning_data.groupby("station_code").sum()
evening_station_sum = evening_data.groupby("station_code").sum()

In [25]:
# 역 정보 합치기
morning_joined_data = morning_station_sum.join(station_info)
evening_joined_data = evening_station_sum.join(station_info)

In [26]:
# 출근시간 승차 인원 
morining_seoul_in = folium.Map(location=[37.55, 126.98], zoom_start = 12)
HeatMap(data = morning_joined_data[['geo.latitude', 'geo.longitude', 'people_out']]).add_to(morining_seoul_in)

morining_seoul_in

In [27]:
# 출근 시간 하차 인원
# 출근시간 승차 인원 
morining_seoul_out = folium.Map(location=[37.55, 126.98], zoom_start = 12)
HeatMap(data = morning_joined_data[['geo.latitude', 'geo.longitude', 'people_out']]).add_to(morining_seoul_out)

morining_seoul_out

In [28]:
# 퇴근 시간 승차 인원 
evening_seoul_in = folium.Map(location=[37.55, 126.98], zoom_start = 12)
HeatMap(data = morning_joined_data[['geo.latitude', 'geo.longitude', 'people_out']]).add_to(evening_seoul_in)

evening_seoul_in

In [29]:
# 퇴근 시간 하차 인원 
evening_seoul_out = folium.Map(location=[37.55, 126.98], zoom_start = 12)
HeatMap(data = morning_joined_data[['geo.latitude', 'geo.longitude', 'people_out']]).add_to(evening_seoul_out)

evening_seoul_out

### 6장 직접 풀어보기

In [164]:
data['timestamp'] = pd.to_datetime(data['timestamp'])

lunch_data = data[
    (data['timestamp'].dt.hour >= 11) &
    (data['timestamp'].dt.hour <= 14)
]

In [165]:
station_sum = (
    lunch_data
    .groupby('station_code')[['people_in', 'people_out']]
    .sum()
)

In [166]:
# 필요한 행만 추리기
station_info = station_info[['station.code', 'station.name','geo.latitude','geo.longitude']]
data = data[['station_code','people_in','people_out','timestamp']]

data

         station_code  people_in  people_out                 timestamp
0                 150         86          85 2021-01-01 05:00:00+09:00
1                 150        111         355 2021-01-01 06:00:00+09:00
2                 150        157         438 2021-01-01 07:00:00+09:00
3                 150        306         592 2021-01-01 08:00:00+09:00
4                 150        333         841 2021-01-01 09:00:00+09:00
...               ...        ...         ...                       ...
1941548          2828         74         263 2021-12-31 19:00:00+09:00
1941549          2828         73         145 2021-12-31 20:00:00+09:00
1941550          2828         95         209 2021-12-31 21:00:00+09:00
1941551          2828         54         138 2021-12-31 22:00:00+09:00
1941552          2828         18          34 2021-12-31 23:00:00+09:00

[1941553 rows x 4 columns]

In [167]:
joined_data = station_sum.join(station_info.set_index('station.code'))
joined_data

              people_in  people_out station.name  geo.latitude  geo.longitude
station_code
150             2505050     2386392          서울역     37.554648     126.972559
151              824481     1122552           시청     37.564718     126.977108
152             1414527     1829519           종각     37.570161     126.982923
153             1848245     2472974    종로3가|탑골공원     37.571607     126.991806
154             1652295     2041594         종로5가     37.570926     127.001849
...                 ...         ...          ...           ...            ...
2824             604018      448206        단대오거리     37.445210     127.156866
2825             298017      277076           신흥     37.440918     127.147564
2826             339413      271084           수진     37.437428     127.140722
2827             351331      290832           모란     37.432130     127.129087
2828               9598        7953          남위례     37.463170     127.139526

[284 rows x 5 columns]

In [168]:
# 결측제거
joined_data = joined_data.dropna()

In [169]:
# 강남, 강북 구분
gangbuk_gangnam = joined_data['region'] = joined_data['geo.latitude'].apply(
    lambda x: '강북' if x >= 37.55 else '강남'
)

gangbuk_gangnam

station_code
150     강북
151     강북
152     강북
153     강북
154     강북
        ..
2824    강남
2825    강남
2826    강남
2827    강남
2828    강남
Name: geo.latitude, Length: 284, dtype: object

In [170]:
# 승차
top3_in = (
    joined_data
    .sort_values(['region', 'people_in'], ascending=[True, False])
    .groupby('region')
    .head(3)
)
top3_in

,people_in,people_out,station.name,geo.latitude,geo.longitude,region
station_code,,,,,,
222,3967332,5009410,강남,37.497175,127.027926,강남
216,3611907,4105618,잠실|송파구청,37.513950,127.102234,강남
230,3521209,2566676,신림,37.484201,126.929715,강남
150,2505050,2386392,서울역,37.554648,126.972559,강북
239,2427533,4667215,홍대입구,37.557192,126.925381,강북
311,2365796,1823729,연신내,37.619001,126.921008,강북

In [171]:
# 하차
top3_out = (
    joined_data
    .sort_values(['region', 'people_out'], ascending=[True, False])
    .groupby('region')
    .head(3)
)
top3_out

,people_in,people_out,station.name,geo.latitude,geo.longitude,region
station_code,,,,,,
222,3967332,5009410,강남,37.497175,127.027926,강남
216,3611907,4105618,잠실|송파구청,37.513950,127.102234,강남
329,3004987,3703051,고속터미널,37.504810,127.004943,강남
239,2427533,4667215,홍대입구,37.557192,126.925381,강북
420,1659526,2651127,혜화,37.582336,127.001844,강북
153,1848245,2472974,종로3가|탑골공원,37.571607,126.991806,강북

2번 문제

In [172]:
# 지도 생성 (서울 중심)
seoul_map = folium.Map(location=[37.55, 126.98], zoom_start=12)

lunch_data_250 = joined_data[joined_data['people_out'] >= 2500000]

for idx, row in lunch_data_250.iterrows():
    folium.Circle(
        location=[row['geo.latitude'], row['geo.longitude']],
        radius=row['people_out'] * 0.0001,  # 0.01%
        color='red',          # 테두리
        fill=True,
        fill_color='red',     # 내부 색
        fill_opacity=0.5
    ).add_to(seoul_map)

seoul_map