In [2]:
import pandas as pd

filePath="C:\data\고등교육기관 하반기 주소록(2025).xlsx"
df_from_excel = pd.read_excel(filePath)
df_from_excel

,고등교육기관 주소록(대학원 외),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,* 조사기준일: 2025. 10. 1. / 자료 추출일: 2026. 1. 20.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"* 일반대학, 교육대학, 산업대학, 방송통신대학교, 기술대학, 각종학교(전문, 대학...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,* 본 자료는 해당기관에서 작성한 자료임,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,연도,학교종류,시도,행정구,학교명,학교명(영문),본분교,학교상태,설립,우편번호,주소,전화번호,팩스번호,홈페이지
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,2025,기능대학,경남,경남 진주시,한국폴리텍 VII 대학 진주캠퍼스,KOREAPOLYTECHNICS JINJU CAMPUS,본교(제1캠퍼스),기존,사립,52766,"경상남도 진주시 모덕로 299 (하대동, 한국폴리텍대학7캠퍼스)",055-752-9901,055-752-0819,NaN
490,2025,기능대학,충남,충남 논산시,한국폴리텍대학바이오캠퍼스,Bio Campus of Korea Polytechnic,본교(제1캠퍼스),기존,사립,32943,"충남 논산시 강경읍 동안로112번길 48(채운리, 한국폴리텍바이오대학)",041-746-7300,041-746-7310,https://www.kopo.ac.kr/bio/index.do
491,2025,기능대학,경북,경북 영천시,한국폴리텍 특성화대학 로봇캠퍼스,Korea Polytechnics Robot Campus,본교(제1캠퍼스),기존,사립,38839,경상북도 영천시 로봇캠퍼스로 1 (화룡동),054-706-1000,054-706-1017,https://www.kopo.ac.kr/robot/index.do
492,2025,기능대학,대구,대구 동구,한국폴리텍대학 영남융합기술캠퍼스,Yeongnam Convergence campus of korea Polytechnic,본교(제1캠퍼스),기존,사립,41027,대구광역시 동구 팔공로 222 (봉무동),053-980-1100,053-980-1129,kopo.ac.kr/yct
493,2025,기능대학,경남,경남 사천시,한국폴리텍대학 항공캠퍼스,Aviation Campus of KOREA POLYTECHNIC,본교(제1캠퍼스),기존,사립,52549,"경상남도 사천시 대학길 46 (이금동, 한국폴리텍항공대학)",055-830-3400,055-830-3414,www.kopo.ac.kr/kapc

In [3]:
df_from_excel.columns = df_from_excel.loc[4].tolist()
df_from_excel

,연도,학교종류,시도,행정구,학교명,학교명(영문),본분교,학교상태,설립,우편번호,주소,전화번호,팩스번호,홈페이지
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,* 조사기준일: 2025. 10. 1. / 자료 추출일: 2026. 1. 20.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"* 일반대학, 교육대학, 산업대학, 방송통신대학교, 기술대학, 각종학교(전문, 대학...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,* 본 자료는 해당기관에서 작성한 자료임,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,연도,학교종류,시도,행정구,학교명,학교명(영문),본분교,학교상태,설립,우편번호,주소,전화번호,팩스번호,홈페이지
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,2025,기능대학,경남,경남 진주시,한국폴리텍 VII 대학 진주캠퍼스,KOREAPOLYTECHNICS JINJU CAMPUS,본교(제1캠퍼스),기존,사립,52766,"경상남도 진주시 모덕로 299 (하대동, 한국폴리텍대학7캠퍼스)",055-752-9901,055-752-0819,NaN
490,2025,기능대학,충남,충남 논산시,한국폴리텍대학바이오캠퍼스,Bio Campus of Korea Polytechnic,본교(제1캠퍼스),기존,사립,32943,"충남 논산시 강경읍 동안로112번길 48(채운리, 한국폴리텍바이오대학)",041-746-7300,041-746-7310,https://www.kopo.ac.kr/bio/index.do
491,2025,기능대학,경북,경북 영천시,한국폴리텍 특성화대학 로봇캠퍼스,Korea Polytechnics Robot Campus,본교(제1캠퍼스),기존,사립,38839,경상북도 영천시 로봇캠퍼스로 1 (화룡동),054-706-1000,054-706-1017,https://www.kopo.ac.kr/robot/index.do
492,2025,기능대학,대구,대구 동구,한국폴리텍대학 영남융합기술캠퍼스,Yeongnam Convergence campus of korea Polytechnic,본교(제1캠퍼스),기존,사립,41027,대구광역시 동구 팔공로 222 (봉무동),053-980-1100,053-980-1129,kopo.ac.kr/yct
493,2025,기능대학,경남,경남 사천시,한국폴리텍대학 항공캠퍼스,Aviation Campus of KOREA POLYTECHNIC,본교(제1캠퍼스),기존,사립,52549,"경상남도 사천시 대학길 46 (이금동, 한국폴리텍항공대학)",055-830-3400,055-830-3414,www.kopo.ac.kr/kapc

In [4]:
df_from_excel = df_from_excel.drop(index=list(range(0,5)))
df_from_excel.head()

,연도,학교종류,시도,행정구,학교명,학교명(영문),본분교,학교상태,설립,우편번호,주소,전화번호,팩스번호,홈페이지
5,2025,대학교,강원,강원 원주시,국립강릉원주대학교,Gangneung-Wonju National University,본교(제2캠퍼스),기존,국립,26403,"강원도 원주시 흥업면 남원로 150 (흥업리, 강릉원주대학교원주캠퍼스)",033-760-8114,033-760-8019,https://www.gwnu.ac.kr/
6,2025,대학교,강원,강원 강릉시,국립강릉원주대학교,Gangneung-Wonju National University,본교(제1캠퍼스),기존,국립,25457,"강원도 강릉시 죽헌길 7 (지변동, 강릉원주대학교)",033-640-7001,033-643-7110,https://www.gwnu.ac.kr/
7,2025,대학교,강원,강원 춘천시,강원대학교,Kangwon National University,본교(제1캠퍼스),기존,국립,24341,"강원도 춘천시 강원대학길 1 (효자동, 강원대학교)",033-250-6114,033-251-9556,www.kangwon.ac.kr/
8,2025,대학교,강원,강원 삼척시,강원대학교,Kangwon National University,본교(제2캠퍼스),기존,국립,25913,"강원도 삼척시 중앙로 346 (교동, 강원대학교삼척캠퍼스)",033-570-6114,033-572-8620,www.kangwon.ac.kr/
9,2025,대학교,대구,대구 중구,경북대학교,Kyungpook National University,본교(제2캠퍼스),기존,국립,41944,대구 중구 국채보상로 680,053-950-5114,NaN,www.knu.ac.kr

In [5]:
print(df_from_excel['학교명'].values)
print(df_from_excel['주소'].values)

['국립강릉원주대학교' '국립강릉원주대학교' '강원대학교' '강원대학교' '경북대학교' '경북대학교' '경북대학교' '경상국립대학교'
 '경상국립대학교' '경상국립대학교' '국립공주대학교' '국립공주대학교' '국립공주대학교' '국립군산대학교' '국립금오공과대학교'
 '국립목포대학교' '국립목포해양대학교' '국립부경대학교' '부산대학교' '부산대학교' '부산대학교' '서울대학교' '서울대학교'
 '서울대학교' '국립순천대학교' '국립경국대학교' '국립경국대학교' '전남대학교' '전남대학교' '전북대학교' '전북대학교'
 '제주대학교' '국립창원대학교' '충남대학교' '충북대학교' '한국교원대학교' '한국체육대학교' '국립한국해양대학교'
 '국립한국교통대학교' '국립한국교통대학교' '국립한국교통대학교' '경남과학기술대학교' '서울과학기술대학교' '한경국립대학교'
 '한경국립대학교' '국립한밭대학교' '서울시립대학교' '인천대학교' '가야대학교' '가야대학교' '가톨릭대학교' '가톨릭대학교'
 '가톨릭대학교' '감리교신학대학교' '강남대학교' '건국대학교' '건국대학교' '건양대학교' '건양대학교' '경기대학교'
 '경기대학교' '경남대학교' '경동대학교' '경동대학교' '경동대학교' '대구한의대학교' '경성대학교' '가천대학교' '가천대학교'
 '경일대학교' '신경주대학교' '경희대학교' '경희대학교' '계명대학교' '계명대학교' '고려대학교' '고려대학교 세종캠퍼스'
 '고신대학교' '고신대학교' '가톨릭관동대학교' '광신대학교' '광운대학교' '광주가톨릭대학교' '광주여자대학교' '국민대학교'
 '강서대학교' '극동대학교' '나사렛대학교' '단국대학교' '단국대학교' '대구대학교' '대구대학교' '대구예술대학교'
 '대구가톨릭대학교' '대구가톨릭대학교' '대구가톨릭대학교' '세한대학교' '세한대학교' '대신대학교' '대전가톨릭대학교'
 '대전대학교' '대진대학교' '서울기독대학교' '덕성여자대학교' '동국대학교' '동국대학교' '동국대학교' '동덕여자대학교'
 '동서대학교' '동서대학교' '동신대학교' '동아대학교' '동아대학교' '동양대학교' '동양대학교' '동의대학교' '루터대학교'
 '명지대학교' '명지대학교' '목원대학교' '배재대학교' '부산가톨릭대학교' '부산외국어대학교' '삼육대학교' '상명대학교'
 '상명대학교' '상지대학교' '서강대학교' '서경대학교' '서울신학대학교' '서울여자대학교' '서울장신대학교' '서원대학교'
 '선문대학교' '성결대학교' '성공회대학교' '성균관대학교' '성균관대학교' '성신여자대학교' '성신여자대학교' '세명대학교'
 '세종대학교' '수원가톨릭대학교' '수원대학교' '숙명여자대학교' '순천향대학교' '순천향대학교' '숭실대학교' '신라대학교'
 '아신대학교' '아주대학교' '안양대학교' '안양대학교' '연세대학교' '연세대학교' '연세대학교 미래캠퍼스' '영남대학교'
 '영남대학교' '영남신학대학교' '유원대학교' '유원대학교' '영산선학대학교' '용인대학교' '우석대학교' '우석대학교'
 '울산대학교' '원광대학교' '위덕대학교' '을지대학교' '을지대학교' '을지대학교' '이화여자대학교' '이화여자대학교'
 '인제대학교' '인제대학교' '인천가톨릭대학교' '인천가톨릭대학교' '인하대학교' '장로회신학대학교' '전주대학교' '조선대학교'
 '중부대학교' '중부대학교' '중앙대학교' '중앙대학교' '중앙승가대학교' '백석대학교' '청주대학교' '청주대학교' '총신대학교'
 '추계예술대학교' '한국침례신학대학교' '칼빈대학교' '평택대학교' '차의과학대학교' '포항공과대학교' '한국기술교육대학교'
 '한국성서대학교' '한국외국어대학교' '한국외국어대학교' '한국항공대학교' '한남대학교' '한남대학교' '한동대학교' '한라대학교'
 '한림대학교' '한서대학교' '한서대학교' '한성대학교' '한세대학교' '한신대학교' '한양대학교' '한양대학교' '서울한영대학교'
 '한일장신대학교' '협성대학교' '호남대학교' '호남신학대학교' '호서대학교' '호서대학교' '호서대학교' '홍익대학교'
 '홍익대학교 세종캠퍼스' '가톨릭꽃동네대학교' '남부대학교' '예원예술대학교' '예원예술대학교' '목포가톨릭대학교'
 '부산장신대학교' '금강대학교' '예수대학교' '광주대학교' '화성의과학대학교' '동명대학교' '영산대학교' '영산대학교'
 '대전신학대학교' '중원대학교' '우송대학교' '김천대학교' '송원대학교' '경운대학교' '남서울대학교' '초당대학교'
 '한국공학대학교' '제주국제대학교' '창신대학교' '신한대학교' '신한대학교' '울산과학기술원' '공주교육대학교' '광주교육대학교'
 '대구교육대학교' '부산교육대학교' '서울교육대학교' '경인교육대학교' '경인교육대학교' '전주교육대학교' '진주교육대학교'
 '청주교육대학교' '춘천교육대학교' '국립한밭대학교' '한국산업기술대학교' '한국방송통신대학교' '우송대학교(산업대)'
 '호원대학교' '청운대학교' '청운대학교' '정석대학' '삼성중공업공과대학' 'SPC식품과학대학' '대우조선해양공과대학'
 '현대중공업공과대학' '포스코기술대학' '포스코기술대학' '삼성전자공과대학교' 'KDB금융대학교' 'LH토지주택대학교'
 '국제예술대학교' '백석예술대학교' '정화예술대학교' '정화예술대학교' '강원도립대학교' '경남도립거창대학' '경남도립남해대학'
 '경북도립대학교' '충북도립대학교' '충북도립대학교' '충남도립대학교' '한국복지대학교' '가톨릭상지대학교' '군산간호대학교'
 '거제대학교' '경남정보대학교' '경남정보대학교' '호산대학교' '경민대학교' '영남외국어대학' '경북전문대학교' '경복대학교'
 '경인여자대학교' '서라벌대학교' '계명문화대학교' '계원예술대학교' '광양보건대학교' '광주보건대학교' '구미대학교'
 '군장대학교' '강동대학교' '나주대학교' '기독간호대학교' '전주기전대학' '경북보건대학교' '김포대학교' '농협대학교'
 '대경대학교' '대경대학교' '대구공업대학교' '대구보건대학교' '수성대학교' '대구과학대학교' '대동대학교' '대림대학교'
 '대원대학교' '동서울대학교' '대전보건대학교' '우송정보대학' '대전과학기술대학교' '아주자동차대학교' '재능대학교'
 '재능대학교' '경북과학대학교' '동남보건대학교' '동강대학교' '동아방송예술대학교' '동아보건대학교' '동양미래대학교'
 '동원대학교' '동의과학대학교' '부산보건대학교' '두원공과대학교' '두원공과대학교' '마산대학교' '명지전문대학'
 '목포과학대학교' '문경대학교' '배화여자대학교' '백제예술대학교' '부산경상대학교' '부산여자대학교' '부산과학기술대학교'
 '부천대학교' '삼육보건대학교' '상지영서대학교' '서영대학교' '서영대학교' '서울여자간호대학교' '서울예술대학교' '서일대학교'
 '성운대학교' '성심외국어대학' '수원여자대학교' '수원여자대학교' '수원과학대학교' '순천제일대학교' '청암대학교'
 '숭의여자대학교' '신구대학교' '신성대학교' '안동과학대학교' '신안산대학교' '안산대학교' '연성대학교' '동원과학기술대학교'
 '여주대학교' '연암공과대학교' '연암대학교' '영남이공대학교' '강릉영동대학교' '세경대학교' '영진전문대학교' '오산대학교'
 '용인예술과학대학교' '울산과학대학교' '울산과학대학교' '한국영상대학교' '원광보건대학교' '유한대학교' '인덕대학교'
 '인하공업전문대학' '장안대학교' '전남과학대학교' '전주비전대학교' '전북과학대학교' '제주관광대학교' '조선이공대학교'
 '조선간호대학교' '충북보건과학대학교' '진주보건대학교' '창원문성대학교' '백석문화대학교' '청강문화산업대학교' '춘해보건대학교'
 '대덕대학교' '충청대학교' '국제대학교' '선린대학교' '포항대학교' '제주한라대학교' '한림성심대학교' '한양여자대학교'
 '한영대학교' '혜전대학교' '경기과학기술대학교' '부산예술대학교' '전남도립대학교' '송호대학교' '한국관광대학교' '서정대학교'
 '송곡대학교' '웅지세무대학교' '김해대학교' '한국승강기대학교' '순복음총회신학교' '세계사이버대학' '영진사이버대학교'
 '한국복지사이버대학교' '경희사이버대학교' '국제사이버대학교' '대구사이버대학교' '부산디지털대학교' '서울디지털대학교'
 '서울사이버대학교' '영남사이버대학교' '세종사이버대학교' '한국열린사이버대학교' '원광디지털대학교' '고려사이버대학교'
 '숭실사이버대학교' '디지털서울문화예술대학교' '한양사이버대학교' '사이버한국외국어대학교' '화신사이버대학교' '글로벌사이버대학교'
 '건양사이버대학교' '태재대학교' '한국과학기술원' '한국과학기술원' '광주과학기술원' '대구경북과학기술원' '한국에너지공과대학교'
 '한국예술종합학교' '한국예술종합학교' '한국전통문화대학교' '한국농수산대학교' '한국골프과학기술대학교' 'ICT폴리텍대학'
 '한국폴리텍대학 서울정수캠퍼스' '한국폴리텍대학 서울강서캠퍼스' '한국폴리텍 I 대학 성남캠퍼스' '한국폴리텍 I 대학 제주캠퍼스'
 '한국폴리텍대학 인천캠퍼스' '한국폴리텍 II 대학 남인천캠퍼스' '한국폴리텍특성화대학 반도체융합캠퍼스'
 '한국폴리텍 II 대학 화성캠퍼스' '한국폴리텍 III 대학 춘천캠퍼스' '한국폴리텍 III 대학 강릉캠퍼스'
 '한국폴리텍 III 대학 원주캠퍼스' '한국폴리텍IV대학 대전캠퍼스' '한국폴리텍IV 대학 청주캠퍼스'
 '한국폴리텍 IV 대학 아산캠퍼스' '한국폴리텍 IV 대학 충남캠퍼스' '한국폴리텍V대학 광주캠퍼스'
 '한국폴리텍 V 대학 전북캠퍼스' '한국폴리텍V대학 전남캠퍼스' '한국폴리텍Ⅴ대학 익산캠퍼스' '한국폴리텍 V 대학 순천캠퍼스'
 '한국폴리텍대학 대구캠퍼스' '한국폴리텍대학 구미캠퍼스' '한국폴리텍 Ⅵ 대학 영주캠퍼스' '한국폴리텍VII대학 창원캠퍼스'
 '한국폴리텍Ⅶ대학 부산캠퍼스' '한국폴리텍 VII 대학 울산캠퍼스' '한국폴리텍 VII 대학 동부산캠퍼스'
 '한국폴리텍 VII 대학 진주캠퍼스' '한국폴리텍대학바이오캠퍼스' '한국폴리텍 특성화대학 로봇캠퍼스'
 '한국폴리텍대학 영남융합기술캠퍼스' '한국폴리텍대학 항공캠퍼스']
['강원도 원주시 흥업면 남원로 150 (흥업리, 강릉원주대학교원주캠퍼스)' '강원도 강릉시 죽헌길 7 (지변동, 강릉원주대학교)'
 '강원도 춘천시 강원대학길 1 (효자동, 강원대학교)' '강원도 삼척시 중앙로 346 (교동, 강원대학교삼척캠퍼스)'
 '대구 중구 국채보상로 680' '대구광역시 북구 대학로 80 (산격동, 경북대학교)' '경북 상주시 경상대로 2559'
 '경남 창원시 의창구 차룡로48번길 54' '경상남도 진주시 진주대로 501 (가좌동, 경상국립대학교 가좌캠퍼스)'
 '경남 통영시 통영해안로 2' '충남 천안시 서북구 천안대로 1223-24'
 '충청남도 공주시 공주대학로 56 (신관동, 국립공주대학교)' '충남 예산군 예산읍 대학로 54'
 '전북특별자치도 군산시 대학로 558 (미룡동, 군산대학교)' '경상북도 구미시 대학로 61 (양호동, 금오공과대학교)'
 '전라남도 무안군 청계면 영산로 1666 (도림리, 국립목포대학교)' '전남 목포시 해양대학로 91'
 '부산광역시 남구 용소로 45 (대연동, 국립부경대학교대연캠퍼스)'
 '부산광역시 금정구 부산대학로63번길 2 (장전동, 부산대학교)' '경남 밀양시 삼랑진읍 삼랑진로 1268-50'
 '경남 양산시 물금읍 부산대학로 49' '서울 종로구 대학로 103' '서울특별시 관악구 관악로 1 (신림동, 서울대학교)'
 '세종특별자치시 집현북로 109' '전라남도 순천시 중앙로 255 (석현동, 순천대학교)'
 '경상북도 안동시 경동로 1375 (송천동)' '경북 예천군 예천읍 도립대학길 114'
 '광주광역시 북구 용봉로 77 (용봉동, 전남대학교)' '전라남도 여수시 대학로 50 (둔덕동, 전남대학교여수캠퍼스)'
 '전북특별자치도 전주시 덕진구 백제대로 567' '전북특별자치도 익산시 고봉로 79'
 '제주특별자치도 제주시 제주대학로 102 (아라일동, 제주대학교)'
 '경상남도 창원시 의창구 창원대학로 20 (사림동, 창원대학교)' '대전광역시 유성구 대학로 99 (궁동, 충남대학교)'
 '충청북도 청주시 서원구 충대로 1 (개신동, 충북대학교)'
 '충청북도 청주시 흥덕구 강내면 태성탑연로 250 (다락리, 한국교원대학교)'
 '서울특별시 송파구 양재대로 1239 (방이동, 한국체육대학교)' '부산광역시 영도구 태종로 727 (동삼동, 국립한국해양대학교)'
 '경기 의왕시 철도박물관로 157' '충북 충주시 대소원면 대학로 50' '충북 증평군 증평읍 대학로 61'
 '경상남도 진주시 동진로 33 (칠암동, 경상국립대학교 칠암캠퍼스)'
 '서울특별시 노원구 공릉로 232 (공릉동, 서울과학기술대학교)' '경기 평택시 한경대학로 35'
 '경기도 안성시 중앙로 327 (석정동)' '대전광역시 유성구 동서대로 125 (덕명동, 한밭대학교)'
 '서울특별시 동대문구 서울시립대로 163 (전농동, 서울시립대학교)' '인천광역시 연수구 아카데미로 119 (송도동, 인천대학교)'
 '경상북도 고령군 대가야읍 대가야로 1103 (지산리, 가야대학교)' '경상남도 김해시 삼계로 208 (삼계동)'
 '서울특별시 종로구 창경궁로 296-12 (혜화동, 가톨릭대학교성신교정)'
 '서울특별시 서초구 반포대로 222 (반포동, 가톨릭대학교 성모병원)'
 '경기도 부천시 원미구 지봉로 43 (역곡동, 가톨릭대학교성심교정)' '서울 서대문구 독립문로 56'
 '경기도 용인시 기흥구 강남로 40 (구갈동, 강남대학교)' '서울특별시 광진구 능동로 120 (화양동, 건국대학교)'
 '충청북도 충주시 충원대로 268 (단월동, 건국대학교GLOCAL캠퍼스)'
 '대전광역시 서구 관저동로 158 (관저동, 건양대학교병원)' '충청남도 논산시 대학로 121 (내동, 건양대학교)'
 '서울특별시 서대문구 경기대로9길 24 (충정로2가, 경기대학교)'
 '경기도 수원시 영통구 광교산로 154-42 (이의동, 경기대학교)'
 '경상남도 창원시 마산합포구 경남대학로 7 (월영동, 경남대학교)' '경기도 양주시 경동대학로 27 (고암동)'
 '강원도 원주시 문막읍 견훤로 815 (후용리, 경동대학교)' '강원도 고성군 토성면 봉포4길 46 (봉포리, 경동대학교)'
 '경북 경산시 한의대로 1' '부산광역시 남구 수영로 309 (대연동, 경성대학교)' '인천 연수구 함박뫼로 191'
 '경기도 성남시 수정구 성남대로 1342 (복정동, 가천대학교)' '경상북도 경산시 하양읍 가마실길 50 (부호리, 경일대학교)'
 '경상북도 경주시 태종로 516 (충효동, 경주대학교)' '서울특별시 동대문구 경희대로 26 (회기동, 경희대학교)'
 '경기 용인시 기흥구 덕영대로 1732' '대구 남구 명덕로 104(대명동, 계명대학교 대명캠퍼스)'
 '대구광역시 달서구 달구벌대로 1095 (신당동, 계명대학교성서캠퍼스)'
 '서울특별시 성북구 안암로 145 (안암동5가, 고려대학교안암캠퍼스(인문사회계))'
 '세종특별자치시 세종로 2511 고려대학교 세종캠퍼스' '부산 서구 감천로 262 (암남동)'
 '부산광역시 영도구 와치로 194 (동삼동, 고신대학교)'
 '강원특별자치도 강릉시 범일로579번길 24 (내곡동, 가톨릭관동대학교)'
 '광주광역시 북구 양산택지소로 36 (본촌동, 광신대학교)' '서울특별시 노원구 광운로 20 (월계동, 광운대학교)'
 '전라남도 나주시 남평읍 중남길 12-25 (남석리, 광주가톨릭대학교)'
 '광주광역시 광산구 광주여대길 40 (산정동, 광주여자대학교도서관/대학본부)'
 '서울특별시 성북구 정릉로 77 (정릉동, 국민대학교)' '서울특별시 강서구 까치산로24길 47 (화곡동, 강서대학교)'
 '충청북도 음성군 감곡면 대학길 76-32 (왕장리, 극동대학교)' '충청남도 천안시 서북구 월봉로 48 (쌍용동, 나사렛대학교)'
 '경기도 용인시 수지구 죽전로 152 (죽전동, 단국대학교죽전캠퍼스)'
 '충청남도 천안시 동남구 단대로 119 (안서동, 단국대학교천안캠퍼스)' '대구광역시 남구 성당로50길 33(대명동, 대구대학교)'
 '경상북도 경산시 진량읍 대구대로 201(내리리, 대구대학교경산캠퍼스)'
 '경상북도 칠곡군 가산면 다부거문1길 202 (다부리, 대구예술대학교)' '대구 중구 명륜로12길 47'
 '대구 남구 두류공원로17길 33' '경상북도 경산시 하양읍 하양로 13-13 (금락리, 대구가톨릭대학교)'
 '충남 당진시 신평면 세한대길 33' '전라남도 영암군 삼호읍 녹색로 1113 (산호리, 세한대학교)'
 '경상북도 경산시 경청로222길 33 (백천동, 대신대학교)'
 '세종특별자치시 전의면 가톨릭대학로 30 (신방리, 대전가톨릭대학교)' '대전광역시 동구 대학로 62 (용운동, 대전대학교)'
 '경기도 포천시 호국로 1007 (선단동, 대진대학교)' '서울특별시 은평구 갈현로4길 26-2 (신사동, 서울기독대학교)'
 '서울특별시 도봉구 삼양로144길 33 (쌍문동, 덕성여자대학교)' '서울특별시 중구 필동로1길 30 (장충동2가, 동국대학교)'
 '경기 고양시 일산동구 동국로 32' '경북 경주시 동대로 123 동국대학교 WISE캠퍼스'
 '서울특별시 성북구 화랑로13길 60 (하월곡동, 동덕여자대학교)' '부산 해운대구 센텀중앙로 55 동서대학교 센텀산학캠퍼스'
 '부산 사상구 주례로 47 동서대학교' '전라남도 나주시 동신대길 67 (대호동, 동신대학교중앙도서관동)'
 '부산 서구 대신공원로 32 (동아대학교)' '부산광역시 사하구 낙동대로550번길 37 (하단동, 동아대학교)'
 '경기도 동두천시 평화로 2741 동양대학교 동두천캠퍼스' '경상북도 영주시 풍기읍 동양대로 145 (산법리, 동양대학교)'
 '부산광역시 부산진구 엄광로 176 (가야동, 동의대학교)' '경기 용인시 기흥구 금화로82번길 20'
 '서울특별시 서대문구 거북골로 34 (남가좌동, 명지대학교)'
 '경기도 용인시 처인구 명지로 116 (남동, 명지대학교 용인캠퍼스)' '대전광역시 서구 도안북로 88 (도안동, 목원대학교)'
 '대전광역시 서구 배재로 155-40 (도마동, 배재대학교)' '부산광역시 금정구 오륜대로 57 (부곡동, 부산가톨릭대학교)'
 '부산광역시 금정구 금샘로485번길 65 (남산동, 부산외국어대학교)' '서울특별시 노원구 화랑로 815 (공릉동, 삼육대학교)'
 '서울특별시 종로구 홍지문2길 20 (홍지동, 상명대학교)'
 '충청남도 천안시 동남구 상명대길 31 (안서동, 상명대학교천안캠퍼스)' '강원도 원주시 상지대길 83 (우산동, 상지대학교)'
 '서울특별시 마포구 백범로 35 (신수동, 서강대학교)' '서울 성북구 서경로 124'
 '경기도 부천시 소사구 호현로489번길 52 (소사본동, 서울신학대학교)'
 '서울특별시 노원구 화랑로 621 (공릉동, 서울여자대학교)' '경기도 광주시 경안로 145 (경안동, 서울장신대학교)'
 '충청북도 청주시 서원구 무심서로 377-3 (모충동, 서원대학교)'
 '충청남도 아산시 탕정면 선문로221번길 70 (갈산리, 선문대학교)'
 '경기도 안양시 만안구 성결대학로 53 (안양동, 성결대학교)' '서울특별시 구로구 연동로 320 (항동, 성공회대학교)'
 '서울특별시 종로구 성균관로 25-2 (명륜3가, 성균관대학교)' '경기 수원시 장안구 서부로 2066'
 '서울특별시 성북구 보문로34다길 2 (돈암동, 성신여자대학교)' '서울 강북구 도봉로76가길 55'
 '충청북도 제천시 세명로 65 (신월동, 세명대학교)' '서울특별시 광진구 능동로 209 (군자동, 세종대학교)'
 '경기도 화성시 봉담읍 왕림1길 67 (왕림리, 수원가톨릭대학교)' '경기도 화성시 봉담읍 와우안길 17 (와우리, 수원대학교)'
 '서울특별시 용산구 청파로47길 100 (청파동2가, 숙명여자대학교)' '충남 천안시 동남구 순천향6길 31'
 '충청남도 아산시 신창면 순천향로 22 (읍내리, 순천향대학교)' '서울시 동작구 상도로 369'
 '부산광역시 사상구 백양대로700번길 140 (괘법동, 신라대학교)'
 '경기도 양평군 옥천면 경강로 1276 (아신리, 아신대학교)' '경기도 수원시 영통구 월드컵로 206 (원천동, 아주대학교)'
 '인천광역시 강화군 불은면 중앙로 602-14 (삼성리, 안양대학교강화캠퍼스)'
 '경기도 안양시 만안구 삼덕로37번길 22 (안양동, 안양대학교)' '서울특별시 서대문구 연세로 50 (신촌동, 연세대학교)'
 '인천 연수구 송도과학로 85' '강원특별자치도 원주시 흥업면 연세대길 1' '대구 남구 현충로 170'
 '경상북도 경산시 대학로 280 (대동, 영남대학교)' '경상북도 경산시 진량읍 봉회1길 26 (봉회리, 영남신학대학교)'
 '충청북도 영동군 영동읍 대학로 310 (설계리, U1대학교)' '충남 아산시 음봉면 연암산로 52-70'
 '전남 영광군 백수읍 성지로 1357 (길용리)' '경기도 용인시 처인구 용인대학로 134 (삼가동, 용인대학교)'
 '충북 진천군 진천읍 대학로 66' '전북특별자치도 완주군 삼례읍 삼례로 443'
 '울산광역시 남구 대학로 93 (무거동, 울산대학교)' '전북특별자치도 익산시 익산대로 460'
 '경상북도 경주시 강동면 동해대로 261 (유금리, 위덕대학교)'
 '대전광역시 중구 계룡로771번길 77 (목동, 을지대학교대전캠퍼스)'
 '경기도 성남시 수정구 산성대로 553 (양지동, 을지대학교)'
 '경기도 의정부시 동일로 712 (금오동, 을지대학교의정부캠퍼스및부속병원)' '서울 서대문구 이화여대길 52'
 '서울 강서구 마곡동로2길 25 (이화여자대학교 의과대학)' '부산광역시 부산진구 복지로 75 (개금동, 부산백병원)'
 '경상남도 김해시 인제로 197 (어방동, 인제대학교)' '인천광역시 연수구 송도문화로120번길 20 (송도동)'
 '인천광역시 강화군 양도면 고려왕릉로 53-1 (도장리)' '인천광역시 미추홀구 인하로 100 (용현동, 인하대학교)'
 '서울특별시 광진구 광장로5길 25-1 (광장동, 장로회신학대학교)' '전북특별자치도 전주시 완산구 천잠로 303'
 '광주광역시 동구 조선대길 146 (서석동)' '경기 고양시 덕양구 동헌로 305'
 '충청남도 금산군 추부면 대학로 201 (마전리, 중부대학교)' '서울특별시 동작구 흑석로 84 (흑석동, 중앙대학교)'
 '경기도 안성시 대덕면 서동대로 4726 (내리, 중앙대학교)' '경기 김포시 승가로 123 (풍무동)'
 '충청남도 천안시 동남구 백석대학로 1 (안서동, 백석대학교,백석문화대학교)'
 '충청북도 청주시 청원구 대성로 298 (내덕동, 청주대학교)' '충청북도 음성군 맹동면 두성리 1040-2, 1063'
 '서울특별시 동작구 사당로 143 (사당동, 총신대학교)' '서울특별시 서대문구 북아현로11가길 7 (북아현동, 추계예술대학교)'
 '대전광역시 유성구 북유성대로 190 (하기동, 침례신학대학교)' '경기도 용인시 기흥구 마북로 184 (마북동, 칼빈대학교)'
 '경기도 평택시 서동대로 3825 (용이동, 평택대학교)' '경기도 포천시 해룡로 120'
 '경상북도 포항시 남구 청암로 77 (지곡동, 포항공과대학교)'
 '충청남도 천안시 동남구 병천면 충절로 1600 (가전리, 한국기술교육대학교)'
 '서울특별시 노원구 동일로214길 32 (상계동, 한국성서대학교)'
 '서울특별시 동대문구 이문로 107 (이문동, 한국외국어대학교)' '경기 용인시 처인구 모현읍 외대로 81'
 '경기도 고양시 덕양구 항공대학로 76 (화전동, 한국항공대학교)' '대전 유성구 유성대로 1646'
 '대전광역시 대덕구 한남로 70 (오정동, 한남대학교)' '경상북도 포항시 북구 흥해읍 한동로 558 (남송리, 한동대학교)'
 '강원도 원주시 흥업면 한라대길 28 (흥업리, 한라대학교)' '강원특별자치도 춘천시 한림대학길 1 (옥천동, 한림대학교)'
 '충청남도 서산시 해미면 한서1로 46 (대곡리, 한서대학교)' '충남 태안군 남면 곰섬로 236-49'
 '서울특별시 성북구 삼선교로16길 116 (삼선동2가, 한성대학교)' '경기도 군포시 한세로 30 (당정동, 한세대학교)'
 '경기도 오산시 한신대길 137 (양산동, 한신대학교)' '서울특별시 성동구 왕십리로 222 (사근동, 한양대학교)'
 '경기도 안산시 상록구 한양대학로 55 (사동, 한양대학교)' '서울특별시 구로구 경인로 290-42 (개봉동, 서울한영대학교)'
 '전북특별자치도 완주군 상관면 왜목로 726-15 (신리, 한일장신대학교)'
 '경기도 화성시 봉담읍 최루백로 72 (상리, 협성대학교)' '광주광역시 광산구 호남대길 120 (서봉동, 호남대학본부)'
 '광주광역시 남구 제중로 77 (양림동, 호남신학대학교)' '충남 천안시 동남구 호서대길 12'
 '충청남도 아산시 배방읍 호서로79번길 20 (세출리, 호서대학교)' '충남 당진시 석문면 산단7로 201'
 '서울특별시 마포구 와우산로 94 (상수동, 홍익대학교)'
 '세종특별자치시 조치원읍 세종로 2639 (신안리, 홍익대학교세종캠퍼스)'
 '충청북도 청주시 서원구 현도면 상삼길 133 (상삼리, 가톨릭꽃동네대학교)' '광주광역시 광산구 남부대길 1 (월계동, 삼애관)'
 '경기도 양주시 은현면 화합로1134번길 110 (용암리, 예원예술대학교양주캠퍼스)' '전북특별자치도 임실군 신평면 창인로 117'
 '전라남도 목포시 영산로 697 (석현동, 목포가톨릭대학교)' '경상남도 김해시 김해대로 1894-68 (구산동)'
 '충남 논산시 상월면 상월로 522 (대명리, 금강대학교)' '전북특별자치도 전주시 완산구 서원로 383'
 '광주광역시 남구 효덕로 277 (진월동, 광주대학교)' '경기도 화성시 남양읍 남양중앙로 400-5 (남양리, 신경대학교)'
 '부산광역시 남구 신선로 428 (용당동, 동명대학교)' '부산 해운대구 반송순환로 142' '경남 양산시 주남로 288'
 '대전광역시 대덕구 한남로 41 (오정동, 대전신학대학교)' '충청북도 괴산군 괴산읍 문무로 85 (동부리, 중원대학교)'
 '대전광역시 동구 동대전로 171 (자양동, 우송정보대학,우송대서캠퍼스)' '경상북도 김천시 대학로 214 (삼락동, 김천대학교)'
 '광주광역시 남구 송암로 73 (송하동, 송원대학)' '경상북도 구미시 산동읍 강동로 730 (인덕리, 경운대학교)'
 '충청남도 천안시 서북구 성환읍 대학로 91 (매주리, 남서울대학교)'
 '전라남도 무안군 무안읍 무안로 380 (성남리, 초당대학교)' '경기도 시흥시 산기대학로 237 (정왕동, 한국공학대학교)'
 '제주특별자치도 제주시 516로 2870 (영평동)' '경남 창원시 마산회원구 팔용로 262, 창신대학교'
 '경기도 의정부시 호암로 95 (호원동, 신한대학교)' '경기도 동두천시 벌마들로40번길 30 (상패동, 신한대학교)'
 '울산광역시 울주군 언양읍 유니스트길 50 (반연리, 울산과학기술대학교)'
 '충청남도 공주시 웅진로 27 (봉황동, 공주교육대학교)' '광주광역시 북구 필문대로 55 (풍향동, 광주교육대학교)'
 '대구광역시 남구 중앙대로 219 (대명동, 대구교육대학교)' '부산광역시 연제구 교대로 24 (거제동, 부산교육대학교)'
 '서울특별시 서초구 서초중앙로 96 (서초동, 서울교육대학교,서울교대초등학교)'
 '인천광역시 계양구 계산로 62 (계산동, 경인교육대학교)' '경기도 안양시 만안구 삼막로 155 (석수동, 경인교육대학교)'
 '전북특별자치도 전주시 완산구 서학로 50' '경상남도 진주시 진양호로369번길 3 (신안동, 진주교육대학교)'
 '충청북도 청주시 서원구 청남로 2065 (수곡동, 청주교육대학교)' '강원특별자치도 춘천시 공지로 126'
 '대전광역시 유성구 동서대로 125 (덕명동, 한밭대학교)' '경기도 시흥시 산기대학로 237 (정왕동, 한국산업기술대학교)'
 '서울특별시 종로구 대학로 86 (동숭동, 한국방송통신대학교)'
 '대전광역시 동구 동대전로 171 (자양동, 우송정보대학,우송대서캠퍼스)' '전북특별자치도 군산시 임피면 호원대3길 64'
 '인천 미추홀구 숙골로 113' '충청남도 홍성군 홍성읍 대학길 25 (남장리, 청운대학교)'
 '서울특별시 강서구 하늘길 260 (공항동, 대한항공)' '경상남도 거제시 장평3로 80 (장평동, 삼성중공업(주)거제조선소)'
 '서울특별시 동작구 신대방16다길 14 (신대방동)' '경상남도 거제시 거제대로 3370 (아주동, 대우조선해양)'
 '울산광역시 동구 방어진순환도로 1000 (전하동, 현대중공업(주))'
 '전남 광양시 금호로 187-7 포스코인재창조원 광양캠퍼스 리더십교육센터'
 '경상북도 포항시 남구 지곡로 120 (지곡동, 포스코인재개발원)' '경기 수원시 장안구 서부로 2066'
 '서울특별시 영등포구 은행로 14 (여의도동, 한국산업은행)'
 '대전광역시 유성구 엑스포로539번길 99 (전민동, LH토지주택연구원)'
 '서울특별시 강남구 도산대로30길 47 (논현동, 국제예술대학교)' '서울특별시 서초구 방배로9길 23 (방배동, 백석예술대학교)'
 '서울 종로구 동숭1길 1' '서울특별시 중구 퇴계로16길 21 (남산동1가, 정화예술대학교명동캠퍼스본관)'
 '강원특별자치도 강릉시 주문진읍 연주로 270 (교항리, 강원도립대학)'
 '경상남도 거창군 거창읍 거창대학로 72 (경남도립거창대학)'
 '경상남도 남해군 남해읍 화전로78번길 30 (남변리, 경남도립남해대학)'
 '경상북도 예천군 예천읍 도립대학길 114 (청복리, 경북도립대학교)' '충북 청주시 흥덕구 오송읍 오송생명1로 194-31'
 '충북 옥천군 옥천읍 대학길 15' '충청남도 청양군 청양읍 학사길 55 (벽천리, 충남도립대학교)'
 '경기도 평택시 삼남로 283 (장안동, 한국복지대학교)' '경상북도 안동시 상지길 45 (율세동, 가톨릭상지대학교)'
 '전북특별자치도 군산시 동개정길 7' '경상남도 거제시 마전1길 91 (장승포동, 거제대학)' '부산 해운대구 센텀중앙로 55'
 '부산광역시 사상구 주례로 45 (주례동, 경남정보대학)' '경상북도 경산시 하양읍 대경로105길 19 (부호리, 호산대학교)'
 '경기도 의정부시 서부로 545 (가능동, 경민대학)' '경상북도 경산시 남천면 남천로 780-9 (협석리, 영남외국어대학)'
 '경상북도 영주시 대학로 77 (휴천동, 경북전문대학교)' '경기도 남양주시 진접읍 경복대로 425 (금곡리, 경복대학교)'
 '인천광역시 계양구 계양산로 63 (계산동, 경인여자대학)' '경상북도 경주시 태종로 516 (충효동, 서라벌대학)'
 '대구광역시 달서구 달서대로 675 (신당동, 계명문화대학교)' '경기도 의왕시 계원대학로 66 (내손동, 계원예술대학교)'
 '전라남도 광양시 광양읍 대학로 85 (덕례리, 광양보건대학)'
 '광주광역시 광산구 북문대로419번길 73 (신창동, 광주보건대학)' '경상북도 구미시 야은로 37 (부곡동, 구미대학교)'
 '전북특별자치도 군산시 성산면 군장대길 13' '충청북도 음성군 감곡면 대학길 278 (단평리, 강동대학교)'
 '전라남도 나주시 다시면 백호로 125 (복암리, 고구려대학)' '광주광역시 남구 백서로70번길 6 (양림동, 기독간호대학)'
 '전북특별자치도 전주시 완산구 전주천서로 267' '경상북도 김천시 대학로 168 (삼락동, 경북보건대학교)'
 '경기도 김포시 월곶면 김포대학로 97 (포내리, 김포대학교)' '경기도 고양시 덕양구 서삼릉길 281 (원당동, 농협대학)'
 '경기 남양주시 진접읍 팔야산단로 58' '경상북도 경산시 자인면 단북1길 65 (단북리, 대경대학)'
 '대구 달서구 송현로 205' '대구광역시 북구 영송로 15 (태전동, 대구보건대학)'
 '대구광역시 수성구 달구벌대로528길 15 (만촌동, 수성대학교)' '대구광역시 북구 영송로 47 (태전동, 대구과학대학)'
 '부산광역시 금정구 동부곡로27번길 88 (부곡동, 대동대학교)' '경기도 안양시 동안구 임곡로 29 (비산동, 대림대학교)'
 '충청북도 제천시 대학로 316 (신월동, 대원대학)' '경기도 성남시 수정구 복정로 76 (복정동, 동서울대학)'
 '대전광역시 동구 충정로 21 (가양동, 대전보건대학)' '대전광역시 동구 백룡로 59 우송정보대학'
 '대전광역시 서구 혜천로 100 (복수동, 대전과학기술대학교)' '충남 보령시 주포면 대학길 106 (아주자동차대학교)'
 '인천광역시 동구 재능로 178 (송림동, 재능대학)' '인천 연수구 송도교육로111번길 15'
 '경상북도 칠곡군 기산면 지산로 634 (봉산리, 경북과학대학교)'
 '경기도 수원시 장안구 천천로74번길 50 (정자동, 동남보건대학)' '광주광역시 북구 동문대로 50 (풍향동, 동강대학교)'
 '경기도 안성시 삼죽면 동아예대길 47 (진촌리, 동아방송예술대학교)'
 '전라남도 영암군 학산면 영산로 76-57 (독천리, 동아보건대학교)'
 '서울특별시 구로구 경인로 445 (고척동, 동양미래대학교)' '경기도 광주시 곤지암읍 경충대로 26 (신촌리, 동원대학)'
 '부산광역시 부산진구 양지로 54 (양정동, 동의과학대학)' '부산광역시 사하구 사리로55번길 16 (괴정동, 부산보건대학)'
 '경기 파주시 파주읍 주라위길 159' '경기도 안성시 죽산면 관음당길 51 (장원리, 두원공과대학교)'
 '경상남도 창원시 마산회원구 내서읍 함마대로 2640 (용담리, 마산대학)'
 '서울특별시 서대문구 가좌로 134 (홍은동, 명지전문대학)' '전라남도 목포시 영산로 413-1 (상동, 목포과학대학)'
 '경상북도 문경시 호계면 대학길 161 (별암리, 문경대학)'
 '서울특별시 종로구 필운대로1길 34 (필운동, 배화여자대학교,배화여자중,고등학교)'
 '전북특별자치도 완주군 봉동읍 백제대학로 171' '부산광역시 연제구 고분로 170 (연산동, 부산경상대학)'
 '부산광역시 부산진구 진남로 506 (양정동, 부산여자대학)'
 '부산광역시 북구 시랑로132번길 88 (구포동, 부산과학기술대학교)'
 '경기도 부천시 원미구 신흥로56번길 25 (심곡동, 부천대학)' '서울특별시 동대문구 망우로 82 (휘경동)'
 '강원도 원주시 상지대길 84 (우산동, 상지영서대학교)' '광주광역시 북구 서강로 1 (운암동, 서영대학교)'
 '경기 파주시 월롱면 서영로 170' '서울특별시 서대문구 간호대로 38 (홍제동, 서울여자간호대학)'
 '경기도 안산시 단원구 예술대학로 171 (고잔동, 서울예술대학)' '서울특별시 중랑구 용마산로90길 28 (면목동, 서일대학)'
 '경상북도 영천시 신녕면 대학길 105 (화남리, 성운대학교)'
 '부산광역시 해운대구 반송순환로 142 (반송동, 영산대학교부산캠퍼스)'
 '경기도 수원시 권선구 온정로 72 (오목천동, 수원여자대학)' '경기 화성시 봉담읍 주석로 1098'
 '경기도 화성시 정남면 세자로 288 (보통리, 수원과학대학)' '전라남도 순천시 제일대학길 17 (덕월동, 순천제일대학)'
 '전라남도 순천시 녹색로 1641 (덕월동, 순천청암대학)' '서울특별시 중구 소파로2길 10 (예장동, 숭의여자대학)'
 '경기도 성남시 중원구 광명로 377 (금광동, 신구대학)' '충청남도 당진시 정미면 대학로 1 (덕마리, 신성대학교)'
 '경상북도 안동시 서후면 서선길 189 (교리, 안동과학대학교)'
 '경기도 안산시 단원구 신안산대학로 135 (초지동, 안산공과대학)'
 '경기도 안산시 상록구 안산대학로 155 (일동, 안산대학교)' '경기도 안양시 만안구 양화로37번길 34 (안양동, 연성대학교)'
 '경상남도 양산시 명곡로 321 (명곡동, 동원과학기술대학교)' '경기도 여주시 세종로 338 (교동, 여주대학)'
 '경상남도 진주시 진주대로629번길 35 (가좌동, 연암공과대학교)'
 '충청남도 천안시 서북구 성환읍 연암로 313 (수향리, 천안연암대학)' '대구광역시 남구 현충로 170 (대명동, 영남이공대학)'
 '강원도 강릉시 공제로 357 (홍제동, 강릉영동대학)' '강원도 영월군 영월읍 하송로 197 (하송리, 세경대학)'
 '대구광역시 북구 복현로 35 (복현동, 영진전문대학)' '경기도 오산시 청학로 45 (청학동, 오산대학)'
 '경기도 용인시 처인구 동부로 61 (마평동, 용인예술과학대학교)' '울산 남구 대학로 57'
 '울산광역시 동구 봉수로 101 (화정동, 울산과학대학동부캠퍼스)'
 '세종특별자치시 장군면 대학길 300 (금암리, 한국영상대학교)' '전북특별자치도 익산시 익산대로 514'
 '경기도 부천시 소사구 경인로 590 (괴안동, 유한대학)' '서울특별시 노원구 초안산로 12 (월계동, 인덕대학)'
 '인천광역시 미추홀구 인하로 100 (용현동, 인하대,인하공전,정석항공고)'
 '경기도 화성시 봉담읍 삼천병마로 1182 (상리, 장안대학)' '전라남도 곡성군 옥과면 대학로 113 (옥과리)'
 '전북특별자치도 전주시 완산구 천잠로 235' '전북특별자치도 정읍시 정읍사로 509'
 '제주특별자치도 제주시 애월읍 평화로 2715 (광령리, 제주관광대학)' '광주 동구 조선이공대길 11(서석동, 조선이공대학교)'
 '광주광역시 동구 조선대2길 70 (서석동, 조선간호대학교)'
 '충청북도 청주시 청원구 내수읍 덕암길 10 (덕암리, 충북보건과학대학교)'
 '경상남도 진주시 의병로 51 (상봉동, 진주보건대학교)' '경상남도 창원시 성산구 충혼로 91 (두대동, 창원문성대학)'
 '충청남도 천안시 동남구 백석대학로 1-2' '경기도 이천시 마장면 청강가창로 389-94 (해월리, 청강문화산업대학)'
 '울산광역시 울주군 웅촌면 대학길 9 (곡천리, 춘해보건대학)' '대전광역시 유성구 가정북로 68 (장동, 대덕대학교)'
 '충청북도 청주시 흥덕구 강내면 월곡길 38 (월곡리, 충청대학)' '경기도 평택시 장안웃길 56 (장안동, 국제대학교)'
 '경상북도 포항시 북구 흥해읍 선린대길 30 (초곡리, 선린대학교)'
 '경상북도 포항시 북구 흥해읍 신덕로 60 (죽천리, 포항대학교)'
 '제주특별자치도 제주시 한라대학로 38 (노형동, 제주한라대학)'
 '강원특별자치도 춘천시 동면 장학길 48 (장학리, 한림성심대학교)' '서울특별시 성동구 살곶이길 200 (사근동, 한양여자대학)'
 '전라남도 여수시 장군산길 18-43 (여서동, 한영대학)' '충청남도 홍성군 홍성읍 대학1길 19 (남장리)'
 '경기도 시흥시 경기과기대로 269 (정왕동, 경기과학기술대학교)'
 '부산광역시 남구 못골번영로71번길 74 (대연동, 부산예술대학)'
 '전라남도 담양군 담양읍 죽녹원로 152 (향교리, 전남도립대학)' '강원도 횡성군 횡성읍 남산로 210 (남산리, 송호대학교)'
 '경기도 이천시 신둔면 이장로311번길 197-73 (고척리, 한국관광대학)'
 '경기도 양주시 은현면 서정로 27 (용암리, 서정대학)' '강원특별자치도 춘천시 남산면 송곡대학길 34 (창촌리, 송곡대학교)'
 '경기도 파주시 탄현면 웅지로144번길 73 (금승리, 웅지세무대학)'
 '경상남도 김해시 삼안로112번길 198 (삼방동, 김해대학교)'
 '경상남도 거창군 거창읍 운정1길 120 (송정리, 한국승강기대학)' '충청북도 제천시 덕산면 도전로 320 (도전리)'
 '경기도 광주시 오포읍 태재로 90 (신현리)' '대구광역시 북구 복현로 35 (복현동, 영진전문대학)'
 '경상북도 경산시 남천면 남천로 746-10 (협석리)' '서울특별시 동대문구 경희대로 26 (회기동, 경희사이버대학교)'
 '경기도 수원시 팔달구 경수대로 490 (인계동)' '경상북도 경산시 진량읍 대구대로 201 (내리리, 대구대학교경산캠퍼스)'
 '부산광역시 사상구 주례로 57 (주례동, 부산디지털대학교)' '서울특별시 강서구 공항대로 424 (화곡동, 서울디지털대학교)'
 '서울특별시 강북구 솔매로49길 60 (미아동, 서울사이버대학교)'
 '경상북도 경산시 남천면 남천로 780-9 (협석리, 영남외국어대학)'
 '서울특별시 광진구 군자로 121 (군자동, 세종사이버대학)' '서울특별시 중랑구 망우로 353 (상봉동, 상봉프레미어스엠코)'
 '전북특별자치도 익산시 익산대로 460' '서울특별시 종로구 북촌로 106 (계동, 고려사이버대학교)'
 '서울특별시 종로구 삼일대로30길 23 (익선동, BIZWELL종로오피스텔)'
 '서울특별시 서대문구 통일로37길 60 (홍제동, 디지털서울문화예술대학교)'
 '서울특별시 성동구 왕십리로 220 (행당동, 한양사이버대학교)' '서울특별시 동대문구 이문로 107 (이문동, 한국외국어대학교)'
 '부산광역시 연제구 고분로191번길 1 (연산동, 화신사이버대학교)' '충남 천안시 동남구 목천읍 교천지산길 284-88'

In [6]:
import requests  # HTTP 요청을 보내기 위한 라이브러리 불러오기
import json

url = 'http://api.vworld.kr/req/address'  # VWorld 주소 → 좌표 변환 API 기본 URL
primary_key = ' DAC1D267-E17C-30B7-B765-F63136205DD1'  # API 인증키

def request_geo(road, addr_type='ROAD'):  # 주소(road)와 주소유형(기본값: 도로명)을 인자로 받는 함수
    params = {
        'service': 'address',    # 사용할 서비스: 주소 서비스
        'request': 'getcoord',   # 요청 유형: 좌표 가져오기
        'version': '2.0',        # API 버전
        'crs': 'epsg:4326',      # 좌표계: WGS84 (위경도 방식)
        'refine': 'true',        # 주소 정제 여부: 사용 -불완전하거나 약식이어도 자동 보정
        'simple': 'false',       # 간략 응답 여부: 상세 결과 반환
        'format': 'json',        # 응답 데이터 형식: JSON
        'type': addr_type,       # 주소 유형: ROAD(도로명) 또는 PARCEL(지번)
        'address': road,         # 좌표로 변환할 주소값
        'key': primary_key       # API 인증키
    }

    page = requests.get(url, params=params)  # API URL에 파라미터를 붙여 GET 요청 전송
    json_data = page.json()  # 응답 결과를 JSON(딕셔너리) 형태로 파싱
    print(json.dumps(json_data, ensure_ascii=False, indent=2)) #한글 깨짐 방지, 들여쓰기 2칸

    if json_data['response']['status'] == 'OK':  # 응답 상태가 정상(OK)인 경우
        x = json_data['response']['result']['point']['x']  # 경도(longitude) 값 추출
        y = json_data['response']['result']['point']['y']  # 위도(latitude) 값 추출
        return x, y  # 경도, 위도 반환
    else:
        return 0, 0  # 요청 실패 시 기본값 0, 0 반환

# 도로명 주소로 좌표 요청 후 x(경도), y(위도)에 저장
x, y = request_geo("인천광역시 부평구 무네미로448번길 56 (구산동, 한국폴리텍Ⅱ대학)")

print(f'x값: {x}')  # 경도 출력
print(f'y값: {y}')  # 위도 출력

{
  "response": {
    "service": {
      "name": "address",
      "version": "2.0",
      "operation": "getcoord",
      "time": "1(ms)"
    },
    "status": "ERROR",
    "error": {
      "level": "2",
      "code": "INVALID_KEY",
      "text": "등록되지 않은 인증키입니다."
    }
  }
}
x값: 0
y값: 0

In [7]:
import pandas as pd                          # 엑셀 파일 읽기용 라이브러리
import requests                              # HTTP 요청 라이브러리
from openpyxl import load_workbook          # 기존 엑셀 파일 불러오기
from openpyxl import Workbook               # 새 엑셀 파일 생성
import re                                   # 정규표현식 라이브러리 (괄호 제거용)


filePath = 'c:\data\고등교육기관 하반기 주소록(2025).xlsx'
df_from_excel = pd.read_excel(filePath) 
df_from_excel.columns = df_from_excel.loc[4].tolist() #엑셀의 5번째 줄(인덱스 4)에 실제 컬럼명(학교명, 주소 등)이 있는 경우
df_from_excel = df_from_excel.drop(index=list(range(0,5)))# 5번째 줄(인덱스 4)을 헤더로 바로 인식하고 그 이전 행은 무시, 제목은 이미 만들었으로 인데스4도 제거


url = 'http://api.vworld.kr/req/address'    # VWorld 주소 → 좌표 변환 API 기본 URL
primary_key = '8FBB6D7A-5A0D-3944-819E-F4018E7414F2'  # API 인증키

def request_geo(road, addr_type='ROAD'):    # 주소와 주소유형(기본값: 도로명)을 인자로 받는 함수
    params = {
        'service': 'address',               # 사용할 서비스: 주소 서비스
        'request': 'getcoord',              # 요청 유형: 좌표 가져오기
        'version': '2.0',                   # API 버전
        'crs': 'epsg:4326',                 # 좌표계: WGS84 (위경도 방식)
        'refine': 'true',                   # 불완전한 주소도 자동 보정
        'simple': 'false',                  # 상세 결과 반환
        'format': 'json',                   # 응답 데이터 형식: JSON
        'type': addr_type,                  # 주소 유형: ROAD(도로명) 또는 PARCEL(지번)
        'address': road,                    # 좌표로 변환할 주소값
        'key': primary_key                  # API 인증키
    }
    page = requests.get(url, params=params) # 파라미터를 붙여 GET 요청 전송
    json_data = page.json()                 # 응답 결과를 딕셔너리로 파싱

    if json_data['response']['status'] == 'OK':  # 응답 상태가 정상인 경우
        x = json_data['response']['result']['point']['x']  # 경도 추출
        y = json_data['response']['result']['point']['y']  # 위도 추출
        return x, y                         # 경도, 위도 반환
    else:
        return 0, 0                         # 실패 시 기본값 반환


# 결과 저장용 엑셀 불러오기 (없으면 새로 생성)
try:
    wb = load_workbook(r"c:\data\학교주소좌표.xlsx", data_only=True)  # 기존 파일 열기
    sheet = wb.active                       # 활성화된 시트 선택
except:
    wb = Workbook()                         # 파일 없으면 새 워크북 생성
    sheet = wb.active                       # 기본 시트 선택

university_list = df_from_excel['학교명'].to_list()  # 학교명 컬럼을 리스트로 변환
address_list = df_from_excel['주소'].to_list()       # 주소 컬럼을 리스트로 변환

for num, value in enumerate(address_list):           # 주소 리스트를 인덱스와 함께 순회
    addr = re.sub(r'\([^)]*\)', '', value)           # 괄호와 괄호 안 내용 제거 ex) (구산동) → 삭제
    addr = addr.strip()                              # 앞뒤 공백 제거
    print(addr)                                      # 정제된 주소 출력
    x, y = request_geo(addr)                         # 주소로 좌표 요청
    sheet.append([university_list[num], addr, x, y]) # 학교명, 주소, 경도, 위도를 한 행으로 추가

wb.save(r"c:\data\학교주소좌표.xlsx")               # 결과 엑셀 파일 저장

강원도 원주시 흥업면 남원로 150
강원도 강릉시 죽헌길 7
강원도 춘천시 강원대학길 1
강원도 삼척시 중앙로 346
대구 중구 국채보상로 680
대구광역시 북구 대학로 80
경북 상주시 경상대로 2559
경남 창원시 의창구 차룡로48번길 54
경상남도 진주시 진주대로 501
경남 통영시 통영해안로 2
충남 천안시 서북구 천안대로 1223-24
충청남도 공주시 공주대학로 56
충남 예산군 예산읍 대학로 54
전북특별자치도 군산시 대학로 558
경상북도 구미시 대학로 61
전라남도 무안군 청계면 영산로 1666
전남 목포시 해양대학로 91
부산광역시 남구 용소로 45
부산광역시 금정구 부산대학로63번길 2
경남 밀양시 삼랑진읍 삼랑진로 1268-50
경남 양산시 물금읍 부산대학로 49
서울 종로구 대학로 103
서울특별시 관악구 관악로 1
세종특별자치시 집현북로 109
전라남도 순천시 중앙로 255
경상북도 안동시 경동로 1375
경북 예천군 예천읍 도립대학길 114
광주광역시 북구 용봉로 77
전라남도 여수시 대학로 50
전북특별자치도 전주시 덕진구 백제대로 567
전북특별자치도 익산시 고봉로 79
제주특별자치도 제주시 제주대학로 102
경상남도 창원시 의창구 창원대학로 20
대전광역시 유성구 대학로 99
충청북도 청주시 서원구 충대로 1
충청북도 청주시 흥덕구 강내면 태성탑연로 250
서울특별시 송파구 양재대로 1239
부산광역시 영도구 태종로 727
경기 의왕시 철도박물관로 157
충북 충주시 대소원면 대학로 50
충북 증평군 증평읍 대학로 61
경상남도 진주시 동진로 33
서울특별시 노원구 공릉로 232
경기 평택시 한경대학로 35
경기도 안성시 중앙로 327
대전광역시 유성구 동서대로 125
서울특별시 동대문구 서울시립대로 163
인천광역시 연수구 아카데미로 119
경상북도 고령군 대가야읍 대가야로 1103
경상남도 김해시 삼계로 208
서울특별시 종로구 창경궁로 296-12
서울특별시 서초구 반포대로 222
경기도 부천시 원미구 지봉로 43
서울 서대문구 독립문로 56
경기도 용인시 기흥구 강남로 40
서울특별시 광진구 능동로 120
충청북도 충주시 충원대로 268
대전광역시 서구 관저동로 158
충청남도 논산시 대학로 121
서울특별시 서대문구 경기대로9길 24
경기도 수원시 영통구 광교산로 154-42
경상남도 창원시 마산합포구 경남대학로 7
경기도 양주시 경동대학로 27
강원도 원주시 문막읍 견훤로 815
강원도 고성군 토성면 봉포4길 46
경북 경산시 한의대로 1
부산광역시 남구 수영로 309
인천 연수구 함박뫼로 191
경기도 성남시 수정구 성남대로 1342
경상북도 경산시 하양읍 가마실길 50
경상북도 경주시 태종로 516
서울특별시 동대문구 경희대로 26
경기 용인시 기흥구 덕영대로 1732
대구 남구 명덕로 104
대구광역시 달서구 달구벌대로 1095
서울특별시 성북구 안암로 145 )
세종특별자치시 세종로 2511 고려대학교 세종캠퍼스
부산 서구 감천로 262
부산광역시 영도구 와치로 194
강원특별자치도 강릉시 범일로579번길 24
광주광역시 북구 양산택지소로 36
서울특별시 노원구 광운로 20
전라남도 나주시 남평읍 중남길 12-25
광주광역시 광산구 광주여대길 40
서울특별시 성북구 정릉로 77
서울특별시 강서구 까치산로24길 47
충청북도 음성군 감곡면 대학길 76-32
충청남도 천안시 서북구 월봉로 48
경기도 용인시 수지구 죽전로 152
충청남도 천안시 동남구 단대로 119
대구광역시 남구 성당로50길 33
경상북도 경산시 진량읍 대구대로 201
경상북도 칠곡군 가산면 다부거문1길 202
대구 중구 명륜로12길 47
대구 남구 두류공원로17길 33
경상북도 경산시 하양읍 하양로 13-13
충남 당진시 신평면 세한대길 33
전라남도 영암군 삼호읍 녹색로 1113
경상북도 경산시 경청로222길 33
세종특별자치시 전의면 가톨릭대학로 30
대전광역시 동구 대학로 62
경기도 포천시 호국로 1007
서울특별시 은평구 갈현로4길 26-2
서울특별시 도봉구 삼양로144길 33
서울특별시 중구 필동로1길 30
경기 고양시 일산동구 동국로 32
경북 경주시 동대로 123 동국대학교 WISE캠퍼스
서울특별시 성북구 화랑로13길 60
부산 해운대구 센텀중앙로 55 동서대학교 센텀산학캠퍼스
부산 사상구 주례로 47 동서대학교
전라남도 나주시 동신대길 67
부산 서구 대신공원로 32
부산광역시 사하구 낙동대로550번길 37
경기도 동두천시 평화로 2741 동양대학교 동두천캠퍼스
경상북도 영주시 풍기읍 동양대로 145
부산광역시 부산진구 엄광로 176
경기 용인시 기흥구 금화로82번길 20
서울특별시 서대문구 거북골로 34
경기도 용인시 처인구 명지로 116
대전광역시 서구 도안북로 88
대전광역시 서구 배재로 155-40
부산광역시 금정구 오륜대로 57
부산광역시 금정구 금샘로485번길 65
서울특별시 노원구 화랑로 815
서울특별시 종로구 홍지문2길 20
충청남도 천안시 동남구 상명대길 31
강원도 원주시 상지대길 83
서울특별시 마포구 백범로 35
서울 성북구 서경로 124
경기도 부천시 소사구 호현로489번길 52
서울특별시 노원구 화랑로 621
경기도 광주시 경안로 145
충청북도 청주시 서원구 무심서로 377-3
충청남도 아산시 탕정면 선문로221번길 70
경기도 안양시 만안구 성결대학로 53
서울특별시 구로구 연동로 320
서울특별시 종로구 성균관로 25-2
경기 수원시 장안구 서부로 2066
서울특별시 성북구 보문로34다길 2
서울 강북구 도봉로76가길 55
충청북도 제천시 세명로 65
서울특별시 광진구 능동로 209
경기도 화성시 봉담읍 왕림1길 67
경기도 화성시 봉담읍 와우안길 17
서울특별시 용산구 청파로47길 100
충남 천안시 동남구 순천향6길 31
충청남도 아산시 신창면 순천향로 22
서울시 동작구 상도로 369
부산광역시 사상구 백양대로700번길 140
경기도 양평군 옥천면 경강로 1276
경기도 수원시 영통구 월드컵로 206
인천광역시 강화군 불은면 중앙로 602-14
경기도 안양시 만안구 삼덕로37번길 22
서울특별시 서대문구 연세로 50
인천 연수구 송도과학로 85
강원특별자치도 원주시 흥업면 연세대길 1
대구 남구 현충로 170
경상북도 경산시 대학로 280
경상북도 경산시 진량읍 봉회1길 26
충청북도 영동군 영동읍 대학로 310
충남 아산시 음봉면 연암산로 52-70
전남 영광군 백수읍 성지로 1357
경기도 용인시 처인구 용인대학로 134
충북 진천군 진천읍 대학로 66
전북특별자치도 완주군 삼례읍 삼례로 443
울산광역시 남구 대학로 93
전북특별자치도 익산시 익산대로 460
경상북도 경주시 강동면 동해대로 261
대전광역시 중구 계룡로771번길 77
경기도 성남시 수정구 산성대로 553
경기도 의정부시 동일로 712
서울 서대문구 이화여대길 52
서울 강서구 마곡동로2길 25
부산광역시 부산진구 복지로 75
경상남도 김해시 인제로 197
인천광역시 연수구 송도문화로120번길 20
인천광역시 강화군 양도면 고려왕릉로 53-1
인천광역시 미추홀구 인하로 100
서울특별시 광진구 광장로5길 25-1
전북특별자치도 전주시 완산구 천잠로 303
광주광역시 동구 조선대길 146
경기 고양시 덕양구 동헌로 305
충청남도 금산군 추부면 대학로 201
서울특별시 동작구 흑석로 84
경기도 안성시 대덕면 서동대로 4726
경기 김포시 승가로 123
충청남도 천안시 동남구 백석대학로 1
충청북도 청주시 청원구 대성로 298
충청북도 음성군 맹동면 두성리 1040-2, 1063
서울특별시 동작구 사당로 143
서울특별시 서대문구 북아현로11가길 7
대전광역시 유성구 북유성대로 190
경기도 용인시 기흥구 마북로 184
경기도 평택시 서동대로 3825
경기도 포천시 해룡로 120
경상북도 포항시 남구 청암로 77
충청남도 천안시 동남구 병천면 충절로 1600
서울특별시 노원구 동일로214길 32
서울특별시 동대문구 이문로 107
경기 용인시 처인구 모현읍 외대로 81
경기도 고양시 덕양구 항공대학로 76
대전 유성구 유성대로 1646
대전광역시 대덕구 한남로 70
경상북도 포항시 북구 흥해읍 한동로 558
강원도 원주시 흥업면 한라대길 28
강원특별자치도 춘천시 한림대학길 1
충청남도 서산시 해미면 한서1로 46
충남 태안군 남면 곰섬로 236-49
서울특별시 성북구 삼선교로16길 116
경기도 군포시 한세로 30
경기도 오산시 한신대길 137
서울특별시 성동구 왕십리로 222
경기도 안산시 상록구 한양대학로 55
서울특별시 구로구 경인로 290-42
전북특별자치도 완주군 상관면 왜목로 726-15
경기도 화성시 봉담읍 최루백로 72
광주광역시 광산구 호남대길 120
광주광역시 남구 제중로 77
충남 천안시 동남구 호서대길 12
충청남도 아산시 배방읍 호서로79번길 20
충남 당진시 석문면 산단7로 201
서울특별시 마포구 와우산로 94
세종특별자치시 조치원읍 세종로 2639
충청북도 청주시 서원구 현도면 상삼길 133
광주광역시 광산구 남부대길 1
경기도 양주시 은현면 화합로1134번길 110
전북특별자치도 임실군 신평면 창인로 117
전라남도 목포시 영산로 697
경상남도 김해시 김해대로 1894-68
충남 논산시 상월면 상월로 522
전북특별자치도 전주시 완산구 서원로 383
광주광역시 남구 효덕로 277
경기도 화성시 남양읍 남양중앙로 400-5
부산광역시 남구 신선로 428
부산 해운대구 반송순환로 142
경남 양산시 주남로 288
대전광역시 대덕구 한남로 41
충청북도 괴산군 괴산읍 문무로 85
대전광역시 동구 동대전로 171
경상북도 김천시 대학로 214
광주광역시 남구 송암로 73
경상북도 구미시 산동읍 강동로 730
충청남도 천안시 서북구 성환읍 대학로 91
전라남도 무안군 무안읍 무안로 380
경기도 시흥시 산기대학로 237
제주특별자치도 제주시 516로 2870
경남 창원시 마산회원구 팔용로 262, 창신대학교
경기도 의정부시 호암로 95
경기도 동두천시 벌마들로40번길 30
울산광역시 울주군 언양읍 유니스트길 50
충청남도 공주시 웅진로 27
광주광역시 북구 필문대로 55
대구광역시 남구 중앙대로 219
부산광역시 연제구 교대로 24
서울특별시 서초구 서초중앙로 96
인천광역시 계양구 계산로 62
경기도 안양시 만안구 삼막로 155
전북특별자치도 전주시 완산구 서학로 50
경상남도 진주시 진양호로369번길 3
충청북도 청주시 서원구 청남로 2065
강원특별자치도 춘천시 공지로 126
대전광역시 유성구 동서대로 125
경기도 시흥시 산기대학로 237
서울특별시 종로구 대학로 86
대전광역시 동구 동대전로 171
전북특별자치도 군산시 임피면 호원대3길 64
인천 미추홀구 숙골로 113
충청남도 홍성군 홍성읍 대학길 25
서울특별시 강서구 하늘길 260
경상남도 거제시 장평3로 80 거제조선소)
서울특별시 동작구 신대방16다길 14
경상남도 거제시 거제대로 3370
울산광역시 동구 방어진순환도로 1000 )
전남 광양시 금호로 187-7 포스코인재창조원 광양캠퍼스 리더십교육센터
경상북도 포항시 남구 지곡로 120
경기 수원시 장안구 서부로 2066
서울특별시 영등포구 은행로 14
대전광역시 유성구 엑스포로539번길 99
서울특별시 강남구 도산대로30길 47
서울특별시 서초구 방배로9길 23
서울 종로구 동숭1길 1
서울특별시 중구 퇴계로16길 21
강원특별자치도 강릉시 주문진읍 연주로 270
경상남도 거창군 거창읍 거창대학로 72
경상남도 남해군 남해읍 화전로78번길 30
경상북도 예천군 예천읍 도립대학길 114
충북 청주시 흥덕구 오송읍 오송생명1로 194-31
충북 옥천군 옥천읍 대학길 15
충청남도 청양군 청양읍 학사길 55
경기도 평택시 삼남로 283
경상북도 안동시 상지길 45
전북특별자치도 군산시 동개정길 7
경상남도 거제시 마전1길 91
부산 해운대구 센텀중앙로 55
부산광역시 사상구 주례로 45
경상북도 경산시 하양읍 대경로105길 19
경기도 의정부시 서부로 545
경상북도 경산시 남천면 남천로 780-9
경상북도 영주시 대학로 77
경기도 남양주시 진접읍 경복대로 425
인천광역시 계양구 계양산로 63
경상북도 경주시 태종로 516
대구광역시 달서구 달서대로 675
경기도 의왕시 계원대학로 66
전라남도 광양시 광양읍 대학로 85
광주광역시 광산구 북문대로419번길 73
경상북도 구미시 야은로 37
전북특별자치도 군산시 성산면 군장대길 13
충청북도 음성군 감곡면 대학길 278
전라남도 나주시 다시면 백호로 125
광주광역시 남구 백서로70번길 6
전북특별자치도 전주시 완산구 전주천서로 267
경상북도 김천시 대학로 168
경기도 김포시 월곶면 김포대학로 97
경기도 고양시 덕양구 서삼릉길 281
경기 남양주시 진접읍 팔야산단로 58
경상북도 경산시 자인면 단북1길 65
대구 달서구 송현로 205
대구광역시 북구 영송로 15
대구광역시 수성구 달구벌대로528길 15
대구광역시 북구 영송로 47
부산광역시 금정구 동부곡로27번길 88
경기도 안양시 동안구 임곡로 29
충청북도 제천시 대학로 316
경기도 성남시 수정구 복정로 76
대전광역시 동구 충정로 21
대전광역시 동구 백룡로 59 우송정보대학
대전광역시 서구 혜천로 100
충남 보령시 주포면 대학길 106
인천광역시 동구 재능로 178
인천 연수구 송도교육로111번길 15
경상북도 칠곡군 기산면 지산로 634
경기도 수원시 장안구 천천로74번길 50
광주광역시 북구 동문대로 50
경기도 안성시 삼죽면 동아예대길 47
전라남도 영암군 학산면 영산로 76-57
서울특별시 구로구 경인로 445
경기도 광주시 곤지암읍 경충대로 26
부산광역시 부산진구 양지로 54
부산광역시 사하구 사리로55번길 16
경기 파주시 파주읍 주라위길 159
경기도 안성시 죽산면 관음당길 51
경상남도 창원시 마산회원구 내서읍 함마대로 2640
서울특별시 서대문구 가좌로 134
전라남도 목포시 영산로 413-1
경상북도 문경시 호계면 대학길 161
서울특별시 종로구 필운대로1길 34
전북특별자치도 완주군 봉동읍 백제대학로 171
부산광역시 연제구 고분로 170
부산광역시 부산진구 진남로 506
부산광역시 북구 시랑로132번길 88
경기도 부천시 원미구 신흥로56번길 25
서울특별시 동대문구 망우로 82
강원도 원주시 상지대길 84
광주광역시 북구 서강로 1
경기 파주시 월롱면 서영로 170
서울특별시 서대문구 간호대로 38
경기도 안산시 단원구 예술대학로 171
서울특별시 중랑구 용마산로90길 28
경상북도 영천시 신녕면 대학길 105
부산광역시 해운대구 반송순환로 142
경기도 수원시 권선구 온정로 72
경기 화성시 봉담읍 주석로 1098
경기도 화성시 정남면 세자로 288
전라남도 순천시 제일대학길 17
전라남도 순천시 녹색로 1641
서울특별시 중구 소파로2길 10
경기도 성남시 중원구 광명로 377
충청남도 당진시 정미면 대학로 1
경상북도 안동시 서후면 서선길 189
경기도 안산시 단원구 신안산대학로 135
경기도 안산시 상록구 안산대학로 155
경기도 안양시 만안구 양화로37번길 34
경상남도 양산시 명곡로 321
경기도 여주시 세종로 338
경상남도 진주시 진주대로629번길 35
충청남도 천안시 서북구 성환읍 연암로 313
대구광역시 남구 현충로 170
강원도 강릉시 공제로 357
강원도 영월군 영월읍 하송로 197
대구광역시 북구 복현로 35
경기도 오산시 청학로 45
경기도 용인시 처인구 동부로 61
울산 남구 대학로 57
울산광역시 동구 봉수로 101
세종특별자치시 장군면 대학길 300
전북특별자치도 익산시 익산대로 514
경기도 부천시 소사구 경인로 590
서울특별시 노원구 초안산로 12
인천광역시 미추홀구 인하로 100
경기도 화성시 봉담읍 삼천병마로 1182
전라남도 곡성군 옥과면 대학로 113
전북특별자치도 전주시 완산구 천잠로 235
전북특별자치도 정읍시 정읍사로 509
제주특별자치도 제주시 애월읍 평화로 2715
광주 동구 조선이공대길 11
광주광역시 동구 조선대2길 70
충청북도 청주시 청원구 내수읍 덕암길 10
경상남도 진주시 의병로 51
경상남도 창원시 성산구 충혼로 91
충청남도 천안시 동남구 백석대학로 1-2
경기도 이천시 마장면 청강가창로 389-94
울산광역시 울주군 웅촌면 대학길 9
대전광역시 유성구 가정북로 68
충청북도 청주시 흥덕구 강내면 월곡길 38
경기도 평택시 장안웃길 56
경상북도 포항시 북구 흥해읍 선린대길 30
경상북도 포항시 북구 흥해읍 신덕로 60
제주특별자치도 제주시 한라대학로 38
강원특별자치도 춘천시 동면 장학길 48
서울특별시 성동구 살곶이길 200
전라남도 여수시 장군산길 18-43
충청남도 홍성군 홍성읍 대학1길 19
경기도 시흥시 경기과기대로 269
부산광역시 남구 못골번영로71번길 74
전라남도 담양군 담양읍 죽녹원로 152
강원도 횡성군 횡성읍 남산로 210
경기도 이천시 신둔면 이장로311번길 197-73
경기도 양주시 은현면 서정로 27
강원특별자치도 춘천시 남산면 송곡대학길 34
경기도 파주시 탄현면 웅지로144번길 73
경상남도 김해시 삼안로112번길 198
경상남도 거창군 거창읍 운정1길 120
충청북도 제천시 덕산면 도전로 320
경기도 광주시 오포읍 태재로 90
대구광역시 북구 복현로 35
경상북도 경산시 남천면 남천로 746-10
서울특별시 동대문구 경희대로 26
경기도 수원시 팔달구 경수대로 490
경상북도 경산시 진량읍 대구대로 201
부산광역시 사상구 주례로 57
서울특별시 강서구 공항대로 424
서울특별시 강북구 솔매로49길 60
경상북도 경산시 남천면 남천로 780-9
서울특별시 광진구 군자로 121
서울특별시 중랑구 망우로 353
전북특별자치도 익산시 익산대로 460
서울특별시 종로구 북촌로 106
서울특별시 종로구 삼일대로30길 23
서울특별시 서대문구 통일로37길 60
서울특별시 성동구 왕십리로 220
서울특별시 동대문구 이문로 107
부산광역시 연제구 고분로191번길 1
충남 천안시 동남구 목천읍 교천지산길 284-88
대전 서구 관저동로 158
서울 종로구 창덕궁5길 22-8
대전 유성구 대학로 291
서울 동대문구 회기로 85
광주광역시 북구 첨단과기로 123
대구 달성군 현풍읍 테크노중앙대로 333
전남 나주시 켄텍길 21
서울특별시 성북구 화랑로32길 146-37
서울 서초구 남부순환로 2374
충청남도 부여군 규암면 백제문로 367
전북특별자치도 전주시 덕진구 콩쥐팥쥐로 1515
강원특별자치도 횡성군 우천면 하대5길 109
경기도 광주시 순암로 16-26
서울특별시 용산구 보광로 73
서울특별시 강서구 우장산로10길 112
경기도 성남시 수정구 수정로 398
제주특별자치도 제주시 산천단동3길 2
인천광역시 부평구 무네미로448번길 56
인천광역시 미추홀구 염전로333번길 23
경기도 안성시 공도읍 송원길 41-12
경기도 화성시 팔탄면 제암고주로 108
강원특별자치도 춘천시 동산면 영서로 1290-31
강원도 강릉시 남산초교길 121
강원도 원주시 북원로2425번길 73
대전광역시 동구 우암로 352-21
충청북도 청주시 흥덕구 산단로 54
충청남도 아산시 신창면 행목로 45
충청남도 홍성군 홍성읍 충서로 1200
광주 북구 하서로 85
전북특별자치도 김제시 백학제길 154
전라남도 무안군 청계면 영산로 1854-16
전북특별자치도 익산시 선화로 579
전라남도 순천시 기적의도서관1길 41
대구광역시 서구 국채보상로43길 15
경북 구미시 수출대로3길 84
경상북도 영주시 가흥로 2
경상남도 창원시 성산구 외동반림로 51-88
부산광역시 북구 만덕대로155번길 99
울산광역시 중구 산전길 155
부산광역시 기장군 정관읍 산단4로 2-69
경상남도 진주시 모덕로 299
충남 논산시 강경읍 동안로112번길 48
경상북도 영천시 로봇캠퍼스로 1
대구광역시 동구 팔공로 222
경상남도 사천시 대학길 46

In [8]:
import pandas as pd
import folium

filePath = r'c:\data\학교주소좌표.xlsx'
df_from_excel = pd.read_excel(filePath,engine='openpyxl',header=None)

df_from_excel.columns = ['학교이름','주소','x','y']

name_list = df_from_excel['학교이름'].to_list()
addr_list = df_from_excel['주소'].to_list()
position_x_list = df_from_excel['x'].to_list()
position_y_list = df_from_excel['y'].to_list()

map = folium.Map(location=[37,127],zoom_start=7)

for i in range(len(name_list)):
    if position_x_list[i] != 0:
        marker = folium.Marker([position_y_list[i],position_x_list[i]],
                            popup=name_list[i], 
                            icon = folium.Icon(color='blue'))
        marker.add_to(map) 
map
# map.save(r'c:\data\uni_map.html')